site_name: lime v0.1.0
site_url: https://mydomain.org/mysite
theme:
  logo: assets/logo.png
  favicon: assets/favicon.png
  homepage: https://bitlaab.com
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/bitlaab
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/bitlaab
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/bitlaab
    - icon: fontawesome/brands/github
      link: https://github.com/bitlaab-bolt
copyright: Copyright © 2024 bitlaab™
